version: '3.8'

services:
  calibre-sync:
    build: .
    container_name: calibre-sync
    restart: unless-stopped
    ports:
      - "${API_PORT:-8001}:8001"
    volumes:
      # Calibre library (mount as read-only recommended)
      - "${CALIBRE_LIBRARY_PATH}:/app/data/calibre-library:ro"
      
      # Replica destinations (adjust paths as needed)
      - "${LOCAL_REPLICA_PATH:-./data/local-replica}:/app/data/local-replica"
      - "${NAS_REPLICA_PATH:-./data/nas-replica}:/app/data/nas-replica"
      
      # Config and logs
      - "${CONFIG_PATH:-./config}:/config"
      - "${LOGS_PATH:-./logs}:/app/logs"
      
    environment:
      # Calibre Configuration
      - CALIBRE_LIBRARY_PATH=/app/data/calibre-library
      - REPLICA_PATHS=/app/data/local-replica,/app/data/nas-replica
      - CALIBRE_CMD_PATH=${CALIBRE_CMD_PATH:-calibredb}
      
      # API Configuration
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-8001}
      - API_DEBUG=${API_DEBUG:-false}
      - API_VERSION=${API_VERSION:-1.0.0}
      
      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=${LOG_FILE:-/app/logs/sync.log}
      
      # Performance Configuration
      - CACHE_TTL=${CACHE_TTL:-300}
      
      # Docker Configuration
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      
    networks:
      - calibre-net
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  calibre-net:
    driver: bridge